controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

profile_complete:
    path: /profile/complete
    controller: App\Controller\ProfileController::completeProfile
    methods: ['GET', 'POST']

